steps:
  - name: 'docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder', '--use' ]
  - name: 'docker'
    args: [ 'buildx', 'build', '--platform', 'linux/amd64,linux/arm64',
            '-t', 'asia-northeast1-docker.pkg.dev/future-309012/image-repo/rust-scratch:1.79-alpine', '--push', '.', ]
